In [1]:
import pandas as pd

In [2]:
df = pd.read_json(
    'crawler-naver-economy-2020.json.bz2',
    compression='bz2',
    orient='records',
    lines=True,
)

In [3]:
df.fillna('', inplace=True)

In [4]:
df.columns

Index(['id', 'idx', 'oid', 'aid', 'officeName', 'title', 'subContent',
       'thumbnail', 'datetime', 'url', 'sectionName', 'type', 'totalCount',
       'category', 'document_id', 'date', 'source', 'source_url',
       'source_section', 'content', 'image_list', 'curl_date', 'vod', 'paper',
       'parsing_error'],
      dtype='object')

In [5]:
df

,id,idx,oid,aid,officeName,title,subContent,thumbnail,datetime,url,...,date,source,source_url,source_section,content,image_list,curl_date,vod,paper,parsing_error
0,109-0004202616,crawler-naver-economy-2020,109,4.20262e+06,OSEN,[사진]위닝시리즈로 시즌 출발하는 두산,"[OSEN=잠실, 최규한 기자] 두산이 LG 상대로 위닝시리즈에 성공했다. 두산은 ...",http://imgnews.naver.net/image/thumb154/109/20...,2020-05-07 21:51:00,https://sports.news.naver.com/kbaseball/news/r...,...,,,,,,,,,,
1,081-0003088644,crawler-naver-economy-2020,81,3.08864e+06,서울신문,한 팀에서도 악연 이어간 정찬헌과 정근우,[서울신문] 7일 개막 잠실 더비에서 정근우가 최주환의 땅볼성 타구를 놓친 뒤 송구...,http://imgnews.naver.net/image/thumb154/081/20...,2020-05-07 21:51:00,https://sports.news.naver.com/kbaseball/news/r...,...,,,,,,,,,,
2,001-0011594638,crawler-naver-economy-2020,1,1.15946e+07,연합뉴스,"라이블리 '파격 대타' 삼성, NC에 개막 3연패","노진혁, 이를 연속 홈런…NC, 삼성전 5연승 NC 노진혁[연합뉴스 자료사진. 재판...",http://imgnews.naver.net/image/thumb154/001/20...,2020-05-07 21:50:00,https://sports.news.naver.com/kbaseball/news/r...,...,,,,,,,,,,
3,410-0000691264,crawler-naver-economy-2020,410,691264,MK스포츠,경기 지켜보는 한용덕 감독 [MK포토],매경닷컴 MK스포츠(인천)=김영구 기자7일 오후 인천 SK행복드림구장에서 '2020...,http://imgnews.naver.net/image/thumb154/410/20...,2020-05-07 21:50:00,https://sports.news.naver.com/kbaseball/news/r...,...,,,,,,,,,,
4,382-0000818453,crawler-naver-economy-2020,382,818453,스포츠동아,[포토] 정찬헌 격려하는 LG 더그아웃,7일 서울 잠실야구장에서 ‘2020 신한은행 SOL KBO리그’ LG 트윈스와 두산...,http://imgnews.naver.net/image/thumb154/382/20...,2020-05-07 21:50:00,https://sports.news.naver.com/kbaseball/news/r...,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2308058,029-0002643746,crawler-naver-economy-2020,,,,[포토] 내년 경제정책방향 발표하는 홍남기 부총리,,,,https://news.naver.com/main/read.nhn?mode=LS2D...,...,2020-12-17 15:17:00+09:00,디지털타임스,http://www.dt.co.kr/contents.html?article_no=2...,경제,홍남기(오른쪽 세번째) 경제부총리 겸 기획재정부 장관이 17일 종로구 세종대로 정부...,[{'image': 'https://imgnews.pstatic.net/image/...,2020-12-17T21:16:41.996315+09:00,,,
2308059,214-0001086798,crawler-naver-economy-2020,,,,"[경제 완전정복] 중국 '회색코뿔소'에 밟히나?, 비트코인 급등은 중국 때문?",,,,https://news.naver.com/main/read.nhn?mode=LS2D...,...,2020-12-17 15:16:00+09:00,MBC,https://imnews.imbc.com/replay/2020/nw1400/art...,경제,"동영상 뉴스\n\t\t\n\t\n\n\n\n\t\n\t[뉴스외전]""中, '회색 코뿔...",,2020-12-17T21:17:04.007520+09:00,"<iframe _src=""/main/readVod.nhn?oid=214&amp;ai...",,
2308060,056-0010954527,crawler-naver-economy-2020,,,,홍남기 부총리 “소상공인 3차 재난지원금 다음 달 지급 목표”,,,,https://news.naver.com/main/read.nhn?mode=LS2D...,...,2020-12-17 15:16:00+09:00,KBS,http://news.kbs.co.kr/news/view.do?ncd=5073852...,경제,홍남기 부총리 겸 기획재정부 장관이 다음 달부터 소상공인에게 3차 재난지원금이 지급...,[{'image': 'https://imgnews.pstatic.net/image/...,2020-12-17T21:17:25.999326+09:00,,,
2308061,215-0000923432,crawler-naver-economy-2020,,,,[단독] `이용자 2천만명` 새마을금고만 금융소비자보호법 열외,,,,https://news.naver.com/main/read.nhn?mode=LS2D...,...,2020-12-17 15:09:00+09:00,한국경제TV,http://news.wowtv.co.kr/NewsCenter/News/Read?a...,경제,동영상 뉴스\n\t\t\n\t\n\n\n\n\t\n\t새마을금고만 금소법 열외\n농...,[{'image': 'https://imgnews.pstatic.net/image/...,2020-12-17T21:17:48.406147+09:00,"<iframe _src=""/main/readVod.nhn?oid=215&amp;ai...",,
2308062,029-0002643836,crawler-naver-economy-2020,,,,내년 연료비 연동제 `脫석탄 영수증` 온다,,,,https://news.naver.com/main/read.nhn?mode=LS2D...,...,2020-12-17 15:00:00+09:00,디지털타임스,http://www.dt.co.kr/contents.html?article_no=2...,경제,'전기요금 체계 개편안' 확정\n\n중장기적으로 요금 계속 오를듯\n\n\n\n오는...,[{'image': 'https://imgnews.pstatic.net/image/...,2020-12-17T21:18:54.702747+09:00,,1면 TOP,

In [6]:
len(df)

2308063

In [7]:
empty_content = df[df['content'] == '']
len(empty_content)

912249

In [9]:
pd.set_option('display.max_rows', None)
empty_content.groupby(by='category').size().to_frame()

                               0
category
IT/모바일                     14430
IT/모바일,사회/사건사고                11
IT/모바일,생활/건강정보                 8
IT/모바일,세계/아시아호주              204
IT/모바일,스포츠/야구                  1
IT/모바일,오피니언                    8
TV                        299740
TV,사회/사건사고                  2645
TV,생활/건강정보                   175
TV,세계/아시아호주                  125
TV,스포츠/야구                   1104
TV,오피니언                      171
TV,정치/청와대                     22
경제/경제 일반                    1721
경제/글로벌 경제                      2
경제/금융                        383
경제/부동산                       110
경제/산업/재계                    1379
경제/생활경제                      316
경제/중기/벤처                      52
경제/증권                      42347
경제/증권,스포츠/야구                   1
사회/사건사고                   110007
사회/사건사고,IT/모바일                 6
사회/사건사고,TV                  1236
사회/사건사고,생활/건강정보               53
사회/사건사고,세계/아시아호주             355
사회/사건사고,세계/아시아호주,오피니언          1
사회/사건사고,스포츠/야구                14
사회/사건사고,오피니언                  54
사회/사건사고,정치/청와대               578
생활/건강정보                    28249
생활/건강정보,IT/모바일                11
생활/건강정보,TV                   205
생활/건강정보,사회/사건사고              370
생활/건강정보,사회/사건사고,세계/아시아호주      11
생활/건강정보,세계/아시아호주            1800
생활/건강정보,스포츠/야구                 1
생활/건강정보,오피니언                  30
생활/건강정보,오피니언,사회/사건사고           1
생활/건강정보,오피니언,세계/아시아호주         16
생활/건강정보,정치/청와대                13
생활/건강정보,정치/청와대,사회/사건사고         1
생활/건강정보,정치/청와대,세계/아시아호주        3
세계/아시아호주                   52392
세계/아시아호주,TV                  266
세계/아시아호주,생활/건강정보             113
세계/아시아호주,오피니언                 39
세계/아시아호주,오피니언,생활/건강정보          1
세계/아시아호주,정치/청와대                3
스포츠/야구                    243335
스포츠/야구,IT/모바일                 23
스포츠/야구,TV                    488
스포츠/야구,사회/사건사고,생활/건강정보         1
스포츠/야구,생활/건강정보                 1
스포츠/야구,오피니언                   33
스포츠/야구,정치/청와대                  1
오피니언                       52193
오피니언,IT/모바일                    1
오피니언,TV                       37
오피니언,사회/사건사고                   4
오피니언,사회/사건사고,세계/아시아호주          1
오피니언,생활/건강정보                   7
오피니언,생활/건강정보,세계/아시아호주          1
오피니언,세계/아시아호주                 40
오피니언,스포츠/야구                   20
오피니언,정치/청와대                   15
정치/청와대                     54969
정치/청와대,IT/모바일                  2
정치/청와대,IT/모바일,사회/사건사고          1
정치/청와대,사회/사건사고                72
정치/청와대,생활/건강정보                 4
정치/청와대,생활/건강정보,사회/사건사고         1
정치/청와대,세계/아시아호주              174
정치/청와대,세계/아시아호주,사회/사건사고        1
정치/청와대,오피니언                   40

In [10]:
content = df[df['content'] != '']
len(content)

1395814

In [11]:
pd.set_option('display.max_rows', None)
content.groupby(by='category').size().to_frame()

                                  0
category
IT/모바일,경제/증권                     80
IT/모바일,경제/증권,세계/아시아호주             4
IT/모바일,경제/증권,정치/청와대               1
TV,경제/증권                         27
경제/경제 일반                     409712
경제/경제 일반,경제/글로벌 경제               18
경제/경제 일반,경제/금융                   14
경제/경제 일반,경제/금융,경제/글로벌 경제          2
경제/경제 일반,경제/부동산                  14
경제/경제 일반,경제/산업/재계                70
경제/경제 일반,경제/산업/재계,경제/생활경제         1
경제/경제 일반,경제/산업/재계,경제/증권           1
경제/경제 일반,경제/생활경제                 10
경제/경제 일반,경제/중기/벤처                 3
경제/경제 일반,경제/증권                   17
경제/글로벌 경제                     23504
경제/글로벌 경제,경제/경제 일반               15
경제/글로벌 경제,경제/금융                   7
경제/글로벌 경제,경제/산업/재계               14
경제/글로벌 경제,경제/산업/재계,경제/증권          1
경제/글로벌 경제,경제/생활경제                 1
경제/글로벌 경제,경제/중기/벤처                1
경제/글로벌 경제,경제/증권                  39
경제/금융                        109522
경제/금융,경제/경제 일반                   12
경제/금융,경제/글로벌 경제                   5
경제/금융,경제/글로벌 경제,경제/증권             2
경제/금융,경제/부동산                      3
경제/금융,경제/산업/재계                    8
경제/금융,경제/생활경제                     5
경제/금융,경제/중기/벤처                    1
경제/금융,경제/중기/벤처,경제/산업/재계           1
경제/금융,경제/증권                      47
경제/금융,경제/증권,경제/산업/재계              1
경제/부동산                       104784
경제/부동산,경제/경제 일반                  24
경제/부동산,경제/금융                      6
경제/부동산,경제/산업/재계                   7
경제/부동산,경제/생활경제                   37
경제/부동산,경제/증권                      1
경제/산업/재계                     309603
경제/산업/재계,경제/경제 일반                70
경제/산업/재계,경제/경제 일반,경제/글로벌 경제       1
경제/산업/재계,경제/글로벌 경제                3
경제/산업/재계,경제/글로벌 경제,경제/금융          1
경제/산업/재계,경제/금융                    3
경제/산업/재계,경제/부동산                   6
경제/산업/재계,경제/부동산,경제/경제 일반          1
경제/산업/재계,경제/부동산,경제/증권             1
경제/산업/재계,경제/생활경제                 72
경제/산업/재계,경제/중기/벤처                 9
경제/산업/재계,경제/중기/벤처,경제/생활경제         1
경제/산업/재계,경제/증권                    6
경제/산업/재계,경제/증권,경제/경제 일반           2
경제/생활경제                       89409
경제/생활경제,경제/경제 일반                  9
경제/생활경제,경제/경제 일반,경제/산업/재계         1
경제/생활경제,경제/글로벌 경제                 3
경제/생활경제,경제/금융                     5
경제/생활경제,경제/부동산                   49
경제/생활경제,경제/산업/재계                 38
경제/생활경제,경제/산업/재계,경제/경제 일반         1
경제/생활경제,경제/중기/벤처                 15
경제/생활경제,경제/중기/벤처,경제/산업/재계         1
경제/생활경제,경제/증권                     1
경제/중기/벤처                      56705
경제/중기/벤처,경제/경제 일반                 2
경제/중기/벤처,경제/금융                    2
경제/중기/벤처,경제/산업/재계                 7
경제/중기/벤처,경제/생활경제                 18
경제/중기/벤처,경제/증권                    1
경제/증권                        288796
경제/증권,IT/모바일                      2
경제/증권,TV                        894
경제/증권,경제/경제 일반                   18
경제/증권,경제/글로벌 경제                  29
경제/증권,경제/금융                      57
경제/증권,경제/부동산,경제/산업/재계             1
경제/증권,경제/산업/재계                    8
경제/증권,경제/생활경제                     2
경제/증권,사회/사건사고                     7
경제/증권,생활/건강정보                     2
경제/증권,세계/아시아호주                 1281
경제/증권,스포츠/야구                      1
경제/증권,오피니언                       15
경제/증권,정치/청와대                     52
사회/사건사고,경제/증권                   175
사회/사건사고,경제/증권,세계/아시아호주            1
사회/사건사고,정치/청와대,경제/증권              5
생활/건강정보,경제/증권                    12
세계/아시아호주,경제/증권                  320
오피니언,경제/증권                       43
정치/청와대,경제/증권                     25